name: build

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: cmake-${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: CMake
        working-directory: ${{github.workspace}}/mastermind
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Make
        working-directory: ${{github.workspace}}/mastermind
        run: cmake --build ./build --config ${{env.BUILD_TYPE}} --verbose
      - name: Test
        working-directory: ${{github.workspace}}/mastermind/build
        #run: ctest -C ${{env.BUILD_TYPE}}
        run: ./mastermind
